server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moduleA
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/moduleA
    user: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: mysql