version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moduleA
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"